/**
 * Audit action types for PIPEDA compliance
 * These actions are logged for security and compliance purposes
 */
export enum AuditAction {
  // Authentication actions
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Email verification
  EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  // Password management
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // OAuth
  OAUTH_LOGIN = 'OAUTH_LOGIN',
  OAUTH_REGISTER = 'OAUTH_REGISTER',

  // PIPEDA Rights
  PROFILE_VIEWED = 'PROFILE_VIEWED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PROFILE_CREATED = 'PROFILE_CREATED',
  DATA_EXPORTED = 'DATA_EXPORTED', // Right to Data Portability
  ACCOUNT_DELETED = 'ACCOUNT_DELETED', // Right to Erasure
  COOKIE_PREFERENCES_UPDATED = 'COOKIE_PREFERENCES_UPDATED', // Right to Withdraw Consent

  // Contractor actions
  LOCATION_UPDATED = 'LOCATION_UPDATED',
  PORTFOLIO_ITEM_ADDED = 'PORTFOLIO_ITEM_ADDED',
  PORTFOLIO_ITEM_UPDATED = 'PORTFOLIO_ITEM_UPDATED',
  PORTFOLIO_ITEM_DELETED = 'PORTFOLIO_ITEM_DELETED',
  CATEGORY_ASSIGNED = 'CATEGORY_ASSIGNED',
  CATEGORY_REMOVED = 'CATEGORY_REMOVED',
  ROLE_SWITCHED = 'ROLE_SWITCHED',

  // Order actions
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_DELETE = 'ORDER_DELETE',
  ORDER_PUBLISH = 'ORDER_PUBLISH',
  ORDER_STATUS_CHANGE = 'ORDER_STATUS_CHANGE',

  // Proposal actions
  PROPOSAL_CREATE = 'PROPOSAL_CREATE',
  PROPOSAL_UPDATE = 'PROPOSAL_UPDATE',
  PROPOSAL_ACCEPT = 'PROPOSAL_ACCEPT',
  PROPOSAL_REJECT = 'PROPOSAL_REJECT',

  // Chat actions (Phase 4)
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
  CHAT_MESSAGE_EDITED = 'CHAT_MESSAGE_EDITED',
  CHAT_MESSAGE_REPORTED = 'CHAT_MESSAGE_REPORTED',
  CHAT_EXPORTED = 'CHAT_EXPORTED',

  // Review actions (Phase 5)
  REVIEW_CREATED = 'REVIEW_CREATED',
  REVIEW_UPDATED = 'REVIEW_UPDATED',
  REVIEW_DELETED = 'REVIEW_DELETED',
  REVIEW_RESPONSE_CREATED = 'REVIEW_RESPONSE_CREATED',
  REVIEW_REPORTED = 'REVIEW_REPORTED',

  // Dispute actions (Phase 7)
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DISPUTE_STATUS_CHANGED = 'DISPUTE_STATUS_CHANGED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_MESSAGE_ADDED = 'DISPUTE_MESSAGE_ADDED',
  DISPUTE_EVIDENCE_UPLOADED = 'DISPUTE_EVIDENCE_UPLOADED',
  DISPUTE_EVIDENCE_DELETED = 'DISPUTE_EVIDENCE_DELETED',

  // Session management
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_DELETED = 'SESSION_DELETED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // CRUD operations (for generic audit interceptor)
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  // System actions
  SYSTEM_ACTION = 'SYSTEM_ACTION',
  SECURITY_ALERT = 'SECURITY_ALERT',
  DATA_CLEANUP = 'DATA_CLEANUP',
}

/**
 * Entity types that can be audited
 */
export enum AuditEntity {
  USER = 'User',
  CONTRACTOR = 'Contractor',
  SESSION = 'Session',
  ORDER = 'Order',
  PROPOSAL = 'Proposal',
  PAYMENT = 'Payment',
  REVIEW = 'Review',
  MESSAGE = 'Message',
  CATEGORY = 'Category',
  PORTFOLIO = 'Portfolio',
  DISPUTE = 'Dispute',
  DISPUTE_EVIDENCE = 'DisputeEvidence',
  DISPUTE_MESSAGE = 'DisputeMessage',
  NOTIFICATION = 'Notification',
  AUDIT_LOG = 'AuditLog',
  SYSTEM = 'System',
}
