/**
 * Dispute reason enum
 * Reasons for initiating a dispute
 */
export enum DisputeReason {
  WORK_NOT_COMPLETED = 'WORK_NOT_COMPLETED',
  WORK_QUALITY_ISSUES = 'WORK_QUALITY_ISSUES',
  LATE_COMPLETION = 'LATE_COMPLETION',
  DIFFERENT_FROM_DESCRIPTION = 'DIFFERENT_FROM_DESCRIPTION',
  CONTRACTOR_UNRESPONSIVE = 'CONTRACTOR_UNRESPONSIVE',
  CLIENT_CHANGED_REQUIREMENTS = 'CLIENT_CHANGED_REQUIREMENTS',
  SAFETY_CONCERNS = 'SAFETY_CONCERNS',
  FRAUDULENT_ACTIVITY = 'FRAUDULENT_ACTIVITY',
  INAPPROPRIATE_BEHAVIOR = 'INAPPROPRIATE_BEHAVIOR',
  OTHER = 'OTHER',
}

