# Filebeat Configuration for Hummii Production
# Ships logs from Docker containers to Logstash

filebeat.inputs:
  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

  # Application logs
  - type: log
    enabled: true
    paths:
      - '/var/log/hummii/api/*.log'
      - '/var/log/hummii/nginx/*.log'
    fields:
      log_type: "application"
      environment: "production"
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  # Security logs
  - type: log
    enabled: true
    paths:
      - '/var/log/hummii/security/*.log'
    fields:
      log_type: "security"
      environment: "production"
    fields_under_root: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Log rotation
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Filebeat registry (for tracking file positions)
filebeat.registry.path: /usr/share/filebeat/data/registry

